server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mail:
    host: smtp.yandex.ru
    port: 465
    username: user_email
    password: user_password #key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
        debug: true
    protocol: smtps
    default-encoding: UTF-8

bank:
  agent:
    url: http://localhost:8082
    out-url: http://localhost:8082
user:
  service:
    url: http://localhost:8081
    out-url: http://localhost:8081